import { describe, expect, it } from "vitest"
import {
  mapGetCoinsRowsToCoinRecords,
  type GetCoinsRow,
} from "./map-get-coins-row"

describe("mapGetCoinsRowsToCoinRecords", () => {
  const createdAt = new Date("2026-06-01T12:00:00.000Z")
  const updatedAt = new Date("2026-06-02T12:00:00.000Z")
  const distributionCreatedAt = new Date("2026-05-15T12:00:00.000Z")
  const distributionUpdatedAt = new Date("2026-05-16T12:00:00.000Z")
  const issuerCreatedAt = new Date("2026-05-01T12:00:00.000Z")
  const issuerUpdatedAt = new Date("2026-05-02T12:00:00.000Z")
  const parentCreatedAt = new Date("2026-04-01T12:00:00.000Z")
  const parentUpdatedAt = new Date("2026-04-02T12:00:00.000Z")
  const rulerCreatedAt = new Date("2026-03-01T12:00:00.000Z")
  const rulerUpdatedAt = new Date("2026-03-02T12:00:00.000Z")
  const rulerGroupCreatedAt = new Date("2026-02-01T12:00:00.000Z")
  const rulerGroupUpdatedAt = new Date("2026-02-02T12:00:00.000Z")
  const referenceCreatedAt = new Date("2026-01-01T12:00:00.000Z")
  const referenceUpdatedAt = new Date("2026-01-02T12:00:00.000Z")
  const referenceCatalogueCreatedAt = new Date("2025-12-01T12:00:00.000Z")
  const referenceCatalogueUpdatedAt = new Date("2025-12-02T12:00:00.000Z")

  it("maps grouped rows into the exact coin record shape", () => {
    const rows: GetCoinsRow[] = [
      {
        id: "coin-1",
        title: "Silver Test Crown",
        createdAt,
        updatedAt,
        minYear: -43,
        maxYear: -41,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: "issuer-parent-1",
        parentIssuerCode: "ancient-world",
        parentIssuerName: "Ancient World",
        parentIssuerCreatedAt: parentCreatedAt,
        parentIssuerUpdatedAt: parentUpdatedAt,
        rulerOrder: 2,
        rulerId: "ruler-1",
        rulerCode: "felipe-vi",
        rulerName: "Felipe VI",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: "ruler-group-1",
        rulerGroupCode: "house-of-bourbon",
        rulerGroupName: "House of Bourbon",
        rulerGroupCreatedAt,
        rulerGroupUpdatedAt,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
      {
        id: "coin-1",
        title: "Silver Test Crown",
        createdAt,
        updatedAt,
        minYear: -43,
        maxYear: -41,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: "issuer-parent-1",
        parentIssuerCode: "ancient-world",
        parentIssuerName: "Ancient World",
        parentIssuerCreatedAt: parentCreatedAt,
        parentIssuerUpdatedAt: parentUpdatedAt,
        rulerOrder: 1,
        rulerId: "ruler-2",
        rulerCode: "juan-carlos-i",
        rulerName: "Juan Carlos I",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
    ]

    expect(mapGetCoinsRowsToCoinRecords(rows)).toStrictEqual([
      {
        id: "coin-1",
        title: "Silver Test Crown",
        createdAt,
        updatedAt,
        issueYearRange: {
          minYear: -43,
          maxYear: -41,
        },
        distribution: {
          id: "distribution-1",
          code: "standard-circulation",
          name: "Standard circulation",
          createdAt: distributionCreatedAt,
          updatedAt: distributionUpdatedAt,
        },
        issuer: {
          id: "issuer-1",
          code: "roman-empire",
          name: "Roman Empire",
          createdAt: issuerCreatedAt,
          updatedAt: issuerUpdatedAt,
          parent: {
            id: "issuer-parent-1",
            code: "ancient-world",
            name: "Ancient World",
            createdAt: parentCreatedAt,
            updatedAt: parentUpdatedAt,
          },
        },
        references: [],
        rulers: [
          {
            id: "ruler-2",
            code: "juan-carlos-i",
            name: "Juan Carlos I",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: null,
          },
          {
            id: "ruler-1",
            code: "felipe-vi",
            name: "Felipe VI",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: {
              id: "ruler-group-1",
              code: "house-of-bourbon",
              name: "House of Bourbon",
              createdAt: rulerGroupCreatedAt,
              updatedAt: rulerGroupUpdatedAt,
            },
          },
        ],
      },
    ])
  })

  it("groups multiplied ruler and catalogue reference rows into one coin without duplicate children", () => {
    const rows: GetCoinsRow[] = [
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        rulerOrder: 2,
        rulerId: "ruler-1",
        rulerCode: "felipe-vi",
        rulerName: "Felipe VI",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: "ruler-group-1",
        rulerGroupCode: "house-of-bourbon",
        rulerGroupName: "House of Bourbon",
        rulerGroupCreatedAt,
        rulerGroupUpdatedAt,
        referenceId: "reference-2",
        referenceType: "catalogue",
        referenceNumber: "K-12",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-2",
        referenceCatalogueCode: "RIC",
        referenceCatalogueTitle: "Roman Imperial Coinage",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        rulerOrder: 1,
        rulerId: "ruler-2",
        rulerCode: "juan-carlos-i",
        rulerName: "Juan Carlos I",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: "reference-1",
        referenceType: "catalogue",
        referenceNumber: "1338A",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-1",
        referenceCatalogueCode: "KM",
        referenceCatalogueTitle: "Standard Catalog of World Coins",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        rulerOrder: 2,
        rulerId: "ruler-1",
        rulerCode: "felipe-vi",
        rulerName: "Felipe VI",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: "ruler-group-1",
        rulerGroupCode: "house-of-bourbon",
        rulerGroupName: "House of Bourbon",
        rulerGroupCreatedAt,
        rulerGroupUpdatedAt,
        referenceId: "reference-1",
        referenceType: "catalogue",
        referenceNumber: "1338A",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-1",
        referenceCatalogueCode: "KM",
        referenceCatalogueTitle: "Standard Catalog of World Coins",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        rulerOrder: 1,
        rulerId: "ruler-2",
        rulerCode: "juan-carlos-i",
        rulerName: "Juan Carlos I",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: "reference-2",
        referenceType: "catalogue",
        referenceNumber: "K-12",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-2",
        referenceCatalogueCode: "RIC",
        referenceCatalogueTitle: "Roman Imperial Coinage",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
    ]

    expect(mapGetCoinsRowsToCoinRecords(rows)).toStrictEqual([
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        issueYearRange: null,
        distribution: {
          id: "distribution-2",
          code: "circulating-commemorative",
          name: "Circulating commemorative",
          createdAt: distributionCreatedAt,
          updatedAt: distributionUpdatedAt,
        },
        issuer: {
          id: "issuer-3",
          code: "spain",
          name: "Spain",
          createdAt: issuerCreatedAt,
          updatedAt: issuerUpdatedAt,
          parent: null,
        },
        rulers: [
          {
            id: "ruler-2",
            code: "juan-carlos-i",
            name: "Juan Carlos I",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: null,
          },
          {
            id: "ruler-1",
            code: "felipe-vi",
            name: "Felipe VI",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: {
              id: "ruler-group-1",
              code: "house-of-bourbon",
              name: "House of Bourbon",
              createdAt: rulerGroupCreatedAt,
              updatedAt: rulerGroupUpdatedAt,
            },
          },
        ],
        references: [
          {
            id: "reference-2",
            type: "catalogue",
            number: "K-12",
            createdAt: referenceCreatedAt,
            updatedAt: referenceUpdatedAt,
            catalogue: {
              id: "catalogue-2",
              code: "RIC",
              title: "Roman Imperial Coinage",
              createdAt: referenceCatalogueCreatedAt,
              updatedAt: referenceCatalogueUpdatedAt,
            },
          },
          {
            id: "reference-1",
            type: "catalogue",
            number: "1338A",
            createdAt: referenceCreatedAt,
            updatedAt: referenceUpdatedAt,
            catalogue: {
              id: "catalogue-1",
              code: "KM",
              title: "Standard Catalog of World Coins",
              createdAt: referenceCatalogueCreatedAt,
              updatedAt: referenceCatalogueUpdatedAt,
            },
          },
        ],
      },
    ])
  })

  it("sets issuer parent to null and rulers to an empty array when the query row has no linked records", () => {
    const row: GetCoinsRow = {
      id: "coin-2",
      title: "Bronze Test Coin",
      createdAt,
      updatedAt,
      minYear: null,
      maxYear: null,
      distributionId: "distribution-1",
      distributionCode: "standard-circulation",
      distributionName: "Standard circulation",
      distributionCreatedAt,
      distributionUpdatedAt,
      issuerId: "issuer-2",
      issuerCode: "athens",
      issuerName: "Athens",
      issuerCreatedAt,
      issuerUpdatedAt,
      parentIssuerId: null,
      parentIssuerCode: null,
      parentIssuerName: null,
      parentIssuerCreatedAt: null,
      parentIssuerUpdatedAt: null,
      rulerOrder: null,
      rulerId: null,
      rulerCode: null,
      rulerName: null,
      rulerCreatedAt: null,
      rulerUpdatedAt: null,
      rulerGroupId: null,
      rulerGroupCode: null,
      rulerGroupName: null,
      rulerGroupCreatedAt: null,
      rulerGroupUpdatedAt: null,
      referenceId: null,
      referenceType: null,
      referenceNumber: null,
      referenceCreatedAt: null,
      referenceUpdatedAt: null,
      referenceCatalogueId: null,
      referenceCatalogueCode: null,
      referenceCatalogueTitle: null,
      referenceCatalogueCreatedAt: null,
      referenceCatalogueUpdatedAt: null,
    }

    expect(mapGetCoinsRowsToCoinRecords([row])).toStrictEqual([
      {
        id: "coin-2",
        title: "Bronze Test Coin",
        createdAt,
        updatedAt,
        issueYearRange: null,
        distribution: {
          id: "distribution-1",
          code: "standard-circulation",
          name: "Standard circulation",
          createdAt: distributionCreatedAt,
          updatedAt: distributionUpdatedAt,
        },
        issuer: {
          id: "issuer-2",
          code: "athens",
          name: "Athens",
          createdAt: issuerCreatedAt,
          updatedAt: issuerUpdatedAt,
          parent: null,
        },
        rulers: [],
        references: [],
      },
    ])
  })
})
