import { describe, expect, it } from "vitest"
import {
  mapGetCoinsRowsToCoinRecords,
  type GetCoinsRow,
} from "./map-get-coins-row"

describe("mapGetCoinsRowsToCoinRecords", () => {
  const createdAt = new Date("2026-06-01T12:00:00.000Z")
  const updatedAt = new Date("2026-06-02T12:00:00.000Z")
  const distributionCreatedAt = new Date("2026-05-15T12:00:00.000Z")
  const distributionUpdatedAt = new Date("2026-05-16T12:00:00.000Z")
  const compositionCreatedAt = new Date("2026-05-12T12:00:00.000Z")
  const compositionUpdatedAt = new Date("2026-05-13T12:00:00.000Z")
  const currencyCreatedAt = new Date("2026-05-10T12:00:00.000Z")
  const currencyUpdatedAt = new Date("2026-05-11T12:00:00.000Z")
  const issuerCreatedAt = new Date("2026-05-01T12:00:00.000Z")
  const issuerUpdatedAt = new Date("2026-05-02T12:00:00.000Z")
  const parentCreatedAt = new Date("2026-04-01T12:00:00.000Z")
  const parentUpdatedAt = new Date("2026-04-02T12:00:00.000Z")
  const rulerCreatedAt = new Date("2026-03-01T12:00:00.000Z")
  const rulerUpdatedAt = new Date("2026-03-02T12:00:00.000Z")
  const rulerGroupCreatedAt = new Date("2026-02-01T12:00:00.000Z")
  const rulerGroupUpdatedAt = new Date("2026-02-02T12:00:00.000Z")
  const themeCreatedAt = new Date("2026-01-15T12:00:00.000Z")
  const themeUpdatedAt = new Date("2026-01-16T12:00:00.000Z")
  const referenceCreatedAt = new Date("2026-01-01T12:00:00.000Z")
  const referenceUpdatedAt = new Date("2026-01-02T12:00:00.000Z")
  const referenceCatalogueCreatedAt = new Date("2025-12-01T12:00:00.000Z")
  const referenceCatalogueUpdatedAt = new Date("2025-12-02T12:00:00.000Z")

  it("maps grouped rows into the exact coin record shape", () => {
    const rows: GetCoinsRow[] = [
      {
        id: "coin-1",
        title: "Silver Test Crown",
        createdAt,
        updatedAt,
        minYear: -43,
        maxYear: -41,
        faceValueText: "2 Euros",
        faceValueNumericValue: 2,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: 4.5,
        diameter: 19.25,
        thickness: 1.75,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-1",
        compositionCode: "silver-900",
        compositionName: "Silver (.900)",
        compositionDescription: "Ninety percent silver alloy.",
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: "issuer-parent-1",
        parentIssuerCode: "ancient-world",
        parentIssuerName: "Ancient World",
        parentIssuerCreatedAt: parentCreatedAt,
        parentIssuerUpdatedAt: parentUpdatedAt,
        mintId: null,
        mintCode: null,
        mintName: null,
        mintCreatedAt: null,
        mintUpdatedAt: null,
        themeId: "theme-2",
        themeCode: "portrait",
        themeName: "Portrait",
        themeCreatedAt,
        themeUpdatedAt,
        rulerOrder: 2,
        rulerId: "ruler-1",
        rulerCode: "felipe-vi",
        rulerName: "Felipe VI",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: "ruler-group-1",
        rulerGroupCode: "house-of-bourbon",
        rulerGroupName: "House of Bourbon",
        rulerGroupCreatedAt,
        rulerGroupUpdatedAt,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
      {
        id: "coin-1",
        title: "Silver Test Crown",
        createdAt,
        updatedAt,
        minYear: -43,
        maxYear: -41,
        faceValueText: "2 Euros",
        faceValueNumericValue: 2,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: 4.5,
        diameter: 19.25,
        thickness: 1.75,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-1",
        compositionCode: "silver-900",
        compositionName: "Silver (.900)",
        compositionDescription: "Ninety percent silver alloy.",
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: "issuer-parent-1",
        parentIssuerCode: "ancient-world",
        parentIssuerName: "Ancient World",
        parentIssuerCreatedAt: parentCreatedAt,
        parentIssuerUpdatedAt: parentUpdatedAt,
        mintId: null,
        mintCode: null,
        mintName: null,
        mintCreatedAt: null,
        mintUpdatedAt: null,
        themeId: "theme-1",
        themeCode: "animal",
        themeName: "Animal",
        themeCreatedAt,
        themeUpdatedAt,
        rulerOrder: 1,
        rulerId: "ruler-2",
        rulerCode: "juan-carlos-i",
        rulerName: "Juan Carlos I",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
    ]

    expect(mapGetCoinsRowsToCoinRecords(rows)).toStrictEqual([
      {
        id: "coin-1",
        title: "Silver Test Crown",
        createdAt,
        updatedAt,
        issueYearRange: {
          minYear: -43,
          maxYear: -41,
        },
        faceValue: {
          text: "2 Euros",
          numericValue: 2,
          currency: {
            id: "currency-1",
            code: "euro",
            name: "Euro",
            fullName: "Euro (2002-date)",
            createdAt: currencyCreatedAt,
            updatedAt: currencyUpdatedAt,
          },
        },
        measurements: {
          weight: 4.5,
          diameter: 19.25,
          thickness: 1.75,
        },
        distribution: {
          id: "distribution-1",
          code: "standard-circulation",
          name: "Standard circulation",
          createdAt: distributionCreatedAt,
          updatedAt: distributionUpdatedAt,
        },
        composition: {
          id: "composition-1",
          code: "silver-900",
          name: "Silver (.900)",
          description: "Ninety percent silver alloy.",
          createdAt: compositionCreatedAt,
          updatedAt: compositionUpdatedAt,
        },
        issuer: {
          id: "issuer-1",
          code: "roman-empire",
          name: "Roman Empire",
          createdAt: issuerCreatedAt,
          updatedAt: issuerUpdatedAt,
          parent: {
            id: "issuer-parent-1",
            code: "ancient-world",
            name: "Ancient World",
            createdAt: parentCreatedAt,
            updatedAt: parentUpdatedAt,
          },
        },
        mints: [],
        themes: [
          {
            id: "theme-1",
            code: "animal",
            name: "Animal",
            createdAt: themeCreatedAt,
            updatedAt: themeUpdatedAt,
          },
          {
            id: "theme-2",
            code: "portrait",
            name: "Portrait",
            createdAt: themeCreatedAt,
            updatedAt: themeUpdatedAt,
          },
        ],
        references: [],
        rulers: [
          {
            id: "ruler-2",
            code: "juan-carlos-i",
            name: "Juan Carlos I",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: null,
          },
          {
            id: "ruler-1",
            code: "felipe-vi",
            name: "Felipe VI",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: {
              id: "ruler-group-1",
              code: "house-of-bourbon",
              name: "House of Bourbon",
              createdAt: rulerGroupCreatedAt,
              updatedAt: rulerGroupUpdatedAt,
            },
          },
        ],
      },
    ])
  })

  it("deduplicates themes and sorts them by name, code, then id", () => {
    const rows: GetCoinsRow[] = [
      {
        id: "coin-theme-1",
        title: "Theme Test Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "1 Euro",
        faceValueNumericValue: 1,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-1",
        compositionCode: "silver-900",
        compositionName: "Silver (.900)",
        compositionDescription: "Ninety percent silver alloy.",
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: null,
        mintCode: null,
        mintName: null,
        mintCreatedAt: null,
        mintUpdatedAt: null,
        themeId: "theme-3",
        themeCode: "portrait",
        themeName: "Portrait",
        themeCreatedAt,
        themeUpdatedAt,
        rulerOrder: null,
        rulerId: null,
        rulerCode: null,
        rulerName: null,
        rulerCreatedAt: null,
        rulerUpdatedAt: null,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
      {
        id: "coin-theme-1",
        title: "Theme Test Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "1 Euro",
        faceValueNumericValue: 1,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-1",
        compositionCode: "silver-900",
        compositionName: "Silver (.900)",
        compositionDescription: "Ninety percent silver alloy.",
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: null,
        mintCode: null,
        mintName: null,
        mintCreatedAt: null,
        mintUpdatedAt: null,
        themeId: "theme-2",
        themeCode: "animal",
        themeName: "Animal",
        themeCreatedAt,
        themeUpdatedAt,
        rulerOrder: null,
        rulerId: null,
        rulerCode: null,
        rulerName: null,
        rulerCreatedAt: null,
        rulerUpdatedAt: null,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
      {
        id: "coin-theme-1",
        title: "Theme Test Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "1 Euro",
        faceValueNumericValue: 1,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-1",
        compositionCode: "silver-900",
        compositionName: "Silver (.900)",
        compositionDescription: "Ninety percent silver alloy.",
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: null,
        mintCode: null,
        mintName: null,
        mintCreatedAt: null,
        mintUpdatedAt: null,
        themeId: "theme-1",
        themeCode: "animal-alt",
        themeName: "Animal",
        themeCreatedAt,
        themeUpdatedAt,
        rulerOrder: null,
        rulerId: null,
        rulerCode: null,
        rulerName: null,
        rulerCreatedAt: null,
        rulerUpdatedAt: null,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
      {
        id: "coin-theme-1",
        title: "Theme Test Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "1 Euro",
        faceValueNumericValue: 1,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-1",
        distributionCode: "standard-circulation",
        distributionName: "Standard circulation",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-1",
        compositionCode: "silver-900",
        compositionName: "Silver (.900)",
        compositionDescription: "Ninety percent silver alloy.",
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-1",
        issuerCode: "roman-empire",
        issuerName: "Roman Empire",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: null,
        mintCode: null,
        mintName: null,
        mintCreatedAt: null,
        mintUpdatedAt: null,
        themeId: "theme-1",
        themeCode: "animal-alt",
        themeName: "Animal",
        themeCreatedAt,
        themeUpdatedAt,
        rulerOrder: null,
        rulerId: null,
        rulerCode: null,
        rulerName: null,
        rulerCreatedAt: null,
        rulerUpdatedAt: null,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: null,
        referenceType: null,
        referenceNumber: null,
        referenceCreatedAt: null,
        referenceUpdatedAt: null,
        referenceCatalogueId: null,
        referenceCatalogueCode: null,
        referenceCatalogueTitle: null,
        referenceCatalogueCreatedAt: null,
        referenceCatalogueUpdatedAt: null,
      },
    ]

    expect(mapGetCoinsRowsToCoinRecords(rows)).toMatchObject([
      {
        id: "coin-theme-1",
        themes: [
          {
            id: "theme-2",
            code: "animal",
            name: "Animal",
          },
          {
            id: "theme-1",
            code: "animal-alt",
            name: "Animal",
          },
          {
            id: "theme-3",
            code: "portrait",
            name: "Portrait",
          },
        ],
      },
    ])
  })

  it("groups multiplied ruler and catalogue reference rows into one coin without duplicate children", () => {
    const rows: GetCoinsRow[] = [
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "50 Euro Cent",
        faceValueNumericValue: 0.5,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-2",
        compositionCode: "copper-nickel",
        compositionName: "Copper-nickel",
        compositionDescription: null,
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: "mint-2",
        mintCode: "royal-mint-of-madrid",
        mintName: "Royal Mint of Madrid",
        mintCreatedAt: new Date("2026-04-10T12:00:00.000Z"),
        mintUpdatedAt: new Date("2026-04-11T12:00:00.000Z"),
        rulerOrder: 2,
        rulerId: "ruler-1",
        rulerCode: "felipe-vi",
        rulerName: "Felipe VI",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: "ruler-group-1",
        rulerGroupCode: "house-of-bourbon",
        rulerGroupName: "House of Bourbon",
        rulerGroupCreatedAt,
        rulerGroupUpdatedAt,
        referenceId: "reference-2",
        referenceType: "catalogue",
        referenceNumber: "K-12",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-2",
        referenceCatalogueCode: "RIC",
        referenceCatalogueTitle: "Roman Imperial Coinage",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "50 Euro Cent",
        faceValueNumericValue: 0.5,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-2",
        compositionCode: "copper-nickel",
        compositionName: "Copper-nickel",
        compositionDescription: null,
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: "mint-1",
        mintCode: "buenos-aires-mint",
        mintName: "Buenos Aires Mint",
        mintCreatedAt: new Date("2026-04-08T12:00:00.000Z"),
        mintUpdatedAt: new Date("2026-04-09T12:00:00.000Z"),
        rulerOrder: 1,
        rulerId: "ruler-2",
        rulerCode: "juan-carlos-i",
        rulerName: "Juan Carlos I",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: "reference-1",
        referenceType: "catalogue",
        referenceNumber: "1338A",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-1",
        referenceCatalogueCode: "KM",
        referenceCatalogueTitle: "Standard Catalog of World Coins",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "50 Euro Cent",
        faceValueNumericValue: 0.5,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-2",
        compositionCode: "copper-nickel",
        compositionName: "Copper-nickel",
        compositionDescription: null,
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: "mint-1",
        mintCode: "buenos-aires-mint",
        mintName: "Buenos Aires Mint",
        mintCreatedAt: new Date("2026-04-08T12:00:00.000Z"),
        mintUpdatedAt: new Date("2026-04-09T12:00:00.000Z"),
        rulerOrder: 2,
        rulerId: "ruler-1",
        rulerCode: "felipe-vi",
        rulerName: "Felipe VI",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: "ruler-group-1",
        rulerGroupCode: "house-of-bourbon",
        rulerGroupName: "House of Bourbon",
        rulerGroupCreatedAt,
        rulerGroupUpdatedAt,
        referenceId: "reference-1",
        referenceType: "catalogue",
        referenceNumber: "1338A",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-1",
        referenceCatalogueCode: "KM",
        referenceCatalogueTitle: "Standard Catalog of World Coins",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        minYear: null,
        maxYear: null,
        faceValueText: "50 Euro Cent",
        faceValueNumericValue: 0.5,
        currencyId: "currency-1",
        currencyCode: "euro",
        currencyName: "Euro",
        currencyFullName: "Euro (2002-date)",
        currencyCreatedAt,
        currencyUpdatedAt,
        weight: null,
        diameter: null,
        thickness: null,
        distributionId: "distribution-2",
        distributionCode: "circulating-commemorative",
        distributionName: "Circulating commemorative",
        distributionCreatedAt,
        distributionUpdatedAt,
        compositionId: "composition-2",
        compositionCode: "copper-nickel",
        compositionName: "Copper-nickel",
        compositionDescription: null,
        compositionCreatedAt,
        compositionUpdatedAt,
        issuerId: "issuer-3",
        issuerCode: "spain",
        issuerName: "Spain",
        issuerCreatedAt,
        issuerUpdatedAt,
        parentIssuerId: null,
        parentIssuerCode: null,
        parentIssuerName: null,
        parentIssuerCreatedAt: null,
        parentIssuerUpdatedAt: null,
        mintId: "mint-2",
        mintCode: "royal-mint-of-madrid",
        mintName: "Royal Mint of Madrid",
        mintCreatedAt: new Date("2026-04-10T12:00:00.000Z"),
        mintUpdatedAt: new Date("2026-04-11T12:00:00.000Z"),
        rulerOrder: 1,
        rulerId: "ruler-2",
        rulerCode: "juan-carlos-i",
        rulerName: "Juan Carlos I",
        rulerCreatedAt,
        rulerUpdatedAt,
        rulerGroupId: null,
        rulerGroupCode: null,
        rulerGroupName: null,
        rulerGroupCreatedAt: null,
        rulerGroupUpdatedAt: null,
        referenceId: "reference-2",
        referenceType: "catalogue",
        referenceNumber: "K-12",
        referenceCreatedAt,
        referenceUpdatedAt,
        referenceCatalogueId: "catalogue-2",
        referenceCatalogueCode: "RIC",
        referenceCatalogueTitle: "Roman Imperial Coinage",
        referenceCatalogueCreatedAt,
        referenceCatalogueUpdatedAt,
      },
    ]

    expect(mapGetCoinsRowsToCoinRecords(rows)).toStrictEqual([
      {
        id: "coin-3",
        title: "Structured Reference Coin",
        createdAt,
        updatedAt,
        issueYearRange: null,
        faceValue: {
          text: "50 Euro Cent",
          numericValue: 0.5,
          currency: {
            id: "currency-1",
            code: "euro",
            name: "Euro",
            fullName: "Euro (2002-date)",
            createdAt: currencyCreatedAt,
            updatedAt: currencyUpdatedAt,
          },
        },
        measurements: {
          weight: null,
          diameter: null,
          thickness: null,
        },
        distribution: {
          id: "distribution-2",
          code: "circulating-commemorative",
          name: "Circulating commemorative",
          createdAt: distributionCreatedAt,
          updatedAt: distributionUpdatedAt,
        },
        composition: {
          id: "composition-2",
          code: "copper-nickel",
          name: "Copper-nickel",
          description: null,
          createdAt: compositionCreatedAt,
          updatedAt: compositionUpdatedAt,
        },
        issuer: {
          id: "issuer-3",
          code: "spain",
          name: "Spain",
          createdAt: issuerCreatedAt,
          updatedAt: issuerUpdatedAt,
          parent: null,
        },
        mints: [
          {
            id: "mint-1",
            code: "buenos-aires-mint",
            name: "Buenos Aires Mint",
            createdAt: new Date("2026-04-08T12:00:00.000Z"),
            updatedAt: new Date("2026-04-09T12:00:00.000Z"),
          },
          {
            id: "mint-2",
            code: "royal-mint-of-madrid",
            name: "Royal Mint of Madrid",
            createdAt: new Date("2026-04-10T12:00:00.000Z"),
            updatedAt: new Date("2026-04-11T12:00:00.000Z"),
          },
        ],
        themes: [],
        rulers: [
          {
            id: "ruler-2",
            code: "juan-carlos-i",
            name: "Juan Carlos I",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: null,
          },
          {
            id: "ruler-1",
            code: "felipe-vi",
            name: "Felipe VI",
            createdAt: rulerCreatedAt,
            updatedAt: rulerUpdatedAt,
            group: {
              id: "ruler-group-1",
              code: "house-of-bourbon",
              name: "House of Bourbon",
              createdAt: rulerGroupCreatedAt,
              updatedAt: rulerGroupUpdatedAt,
            },
          },
        ],
        references: [
          {
            id: "reference-2",
            type: "catalogue",
            number: "K-12",
            createdAt: referenceCreatedAt,
            updatedAt: referenceUpdatedAt,
            catalogue: {
              id: "catalogue-2",
              code: "RIC",
              title: "Roman Imperial Coinage",
              createdAt: referenceCatalogueCreatedAt,
              updatedAt: referenceCatalogueUpdatedAt,
            },
          },
          {
            id: "reference-1",
            type: "catalogue",
            number: "1338A",
            createdAt: referenceCreatedAt,
            updatedAt: referenceUpdatedAt,
            catalogue: {
              id: "catalogue-1",
              code: "KM",
              title: "Standard Catalog of World Coins",
              createdAt: referenceCatalogueCreatedAt,
              updatedAt: referenceCatalogueUpdatedAt,
            },
          },
        ],
      },
    ])
  })

  it("sets issuer parent to null and rulers to an empty array when the query row has no linked records", () => {
    const row: GetCoinsRow = {
      id: "coin-2",
      title: "Bronze Test Coin",
      createdAt,
      updatedAt,
      minYear: null,
      maxYear: null,
      faceValueText: "1 Bronze Unit",
      faceValueNumericValue: 1,
      currencyId: "currency-2",
      currencyCode: "bronze-unit",
      currencyName: "Bronze Unit",
      currencyFullName: "Bronze Unit",
      currencyCreatedAt,
      currencyUpdatedAt,
      weight: null,
      diameter: null,
      thickness: null,
      distributionId: "distribution-1",
      distributionCode: "standard-circulation",
      distributionName: "Standard circulation",
      distributionCreatedAt,
      distributionUpdatedAt,
      compositionId: "composition-3",
      compositionCode: "bronze",
      compositionName: "Bronze",
      compositionDescription: null,
      compositionCreatedAt,
      compositionUpdatedAt,
      issuerId: "issuer-2",
      issuerCode: "athens",
      issuerName: "Athens",
      issuerCreatedAt,
      issuerUpdatedAt,
      parentIssuerId: null,
      parentIssuerCode: null,
      parentIssuerName: null,
      parentIssuerCreatedAt: null,
      parentIssuerUpdatedAt: null,
      mintId: null,
      mintCode: null,
      mintName: null,
      mintCreatedAt: null,
      mintUpdatedAt: null,
      rulerOrder: null,
      rulerId: null,
      rulerCode: null,
      rulerName: null,
      rulerCreatedAt: null,
      rulerUpdatedAt: null,
      rulerGroupId: null,
      rulerGroupCode: null,
      rulerGroupName: null,
      rulerGroupCreatedAt: null,
      rulerGroupUpdatedAt: null,
      referenceId: null,
      referenceType: null,
      referenceNumber: null,
      referenceCreatedAt: null,
      referenceUpdatedAt: null,
      referenceCatalogueId: null,
      referenceCatalogueCode: null,
      referenceCatalogueTitle: null,
      referenceCatalogueCreatedAt: null,
      referenceCatalogueUpdatedAt: null,
    }

    expect(mapGetCoinsRowsToCoinRecords([row])).toStrictEqual([
      {
        id: "coin-2",
        title: "Bronze Test Coin",
        createdAt,
        updatedAt,
        issueYearRange: null,
        faceValue: {
          text: "1 Bronze Unit",
          numericValue: 1,
          currency: {
            id: "currency-2",
            code: "bronze-unit",
            name: "Bronze Unit",
            fullName: "Bronze Unit",
            createdAt: currencyCreatedAt,
            updatedAt: currencyUpdatedAt,
          },
        },
        measurements: {
          weight: null,
          diameter: null,
          thickness: null,
        },
        distribution: {
          id: "distribution-1",
          code: "standard-circulation",
          name: "Standard circulation",
          createdAt: distributionCreatedAt,
          updatedAt: distributionUpdatedAt,
        },
        composition: {
          id: "composition-3",
          code: "bronze",
          name: "Bronze",
          description: null,
          createdAt: compositionCreatedAt,
          updatedAt: compositionUpdatedAt,
        },
        issuer: {
          id: "issuer-2",
          code: "athens",
          name: "Athens",
          createdAt: issuerCreatedAt,
          updatedAt: issuerUpdatedAt,
          parent: null,
        },
        mints: [],
        themes: [],
        rulers: [],
        references: [],
      },
    ])
  })
})
