import type { SeededCoin } from "./types"

export const seededCoins: SeededCoin[] = [
  {
    title: "Spain 2 Euro",
    comments:
      "Common circulating commemorative format with a national obverse and shared euro reverse.",
    compositionCode: "bimetallic",
    compositionDescription:
      "Outer ring: copper-nickel. Core: three layers of nickel-brass, nickel, and nickel-brass.",
    currencyCode: "euro",
    distributionCode: "circulating-commemorative",
    edgeCode: "lettered-signs-numbers-reeded",
    faceValueNumericValue: 2,
    faceValueText: "2 Euros",
    issuerCode: "spain",
    isDemonetized: false,
    mintage: 50000000,
    orientationCode: "medal-alignment",
    techniqueCode: "milled",
    shapeCode: "circular",
    rimCode: "raised-not-decorated-both-sides",
    weight: 8.5,
    diameter: 25.75,
    thickness: 2.2,
    minYear: 2015,
    maxYear: 2026,
    createdAt: new Date("2026-01-11T00:00:00.000Z"),
    updatedAt: new Date("2026-01-11T00:00:00.000Z"),
  },
  {
    title: "Spain 1 Euro",
    compositionCode: "bimetallic",
    compositionDescription:
      "Outer ring: nickel-brass. Core: three layers of copper-nickel, nickel, and copper-nickel.",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Euro",
    issuerCode: "spain",
    orientationCode: "medal-alignment",
    shapeCode: "circular",
    rimCode: "raised-not-decorated-both-sides",
    techniqueCode: "milled",
    weight: 7.5,
    diameter: 23.25,
    thickness: 2.33,
    minYear: 1999,
    maxYear: 2026,
    createdAt: new Date("2026-01-12T00:00:00.000Z"),
    updatedAt: new Date("2026-01-12T00:00:00.000Z"),
  },
]
