import type { SeededCoin } from "./types"

export const seededCoins: SeededCoin[] = [
  {
    title: "Argentina Sol de Mayo Peso",
    compositionCode: "silver-900",
    currencyCode: "argentine-peso",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Peso",
    issuerCode: "argentina",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 12.5,
    diameter: 31.5,
    thickness: 2.4,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    title: "Buenos Aires 8 Reales 1813",
    compositionCode: "silver-900",
    currencyCode: "real",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 8,
    faceValueText: "8 Reales",
    issuerCode: "buenos-aires",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    weight: 26.95,
    diameter: 37.5,
    thickness: 2.1,
    minYear: 1813,
    maxYear: 1813,
    createdAt: new Date("2026-01-02T00:00:00.000Z"),
    updatedAt: new Date("2026-01-02T00:00:00.000Z"),
  },
  {
    title: "United States Lincoln Cent",
    compositionCode: "copper",
    currencyCode: "united-states-dollar",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.01,
    faceValueText: "1 Cent",
    issuerCode: "united-states",
    orientationCode: "coin-alignment",
    techniqueCode: "milled",
    shapeCode: "round",
    rimCode: "plain",
    weight: 3.11,
    diameter: 19.05,
    minYear: 1909,
    maxYear: 1909,
    createdAt: new Date("2026-01-03T00:00:00.000Z"),
    updatedAt: new Date("2026-01-03T00:00:00.000Z"),
  },
  {
    title: "Argentina 20 Centavos",
    compositionCode: "copper-nickel",
    currencyCode: "argentine-peso",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.2,
    faceValueText: "20 Centavos",
    issuerCode: "argentina",
    weight: 10,
    diameter: 27,
    thickness: 2.2,
    minYear: 1896,
    maxYear: 1898,
    createdAt: new Date("2026-01-04T00:00:00.000Z"),
    updatedAt: new Date("2026-01-04T00:00:00.000Z"),
  },
  {
    title: "Buenos Aires 5 Decimos",
    compositionCode: "silver-900",
    currencyCode: "real",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.5,
    faceValueText: "5 Decimos",
    issuerCode: "buenos-aires",
    weight: 8.5,
    diameter: 24,
    thickness: 1.7,
    minYear: 1822,
    maxYear: 1823,
    createdAt: new Date("2026-01-05T00:00:00.000Z"),
    updatedAt: new Date("2026-01-05T00:00:00.000Z"),
  },
  {
    title: "United States National Park Quarter",
    compositionCode: "copper-nickel-clad",
    currencyCode: "united-states-dollar",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.25,
    faceValueText: "Quarter Dollar",
    issuerCode: "united-states",
    orientationCode: "coin-alignment",
    techniqueCode: "milled",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    weight: 8.1,
    diameter: 26.5,
    thickness: 2,
    minYear: 2014,
    maxYear: 2026,
    createdAt: new Date("2026-01-06T00:00:00.000Z"),
    updatedAt: new Date("2026-01-06T00:00:00.000Z"),
  },
  {
    title: "Argentina Copper Peso",
    compositionCode: "copper",
    currencyCode: "argentine-peso",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Peso",
    issuerCode: "argentina",
    diameter: 22,
    createdAt: new Date("2026-01-07T00:00:00.000Z"),
    updatedAt: new Date("2026-01-07T00:00:00.000Z"),
  },
  {
    title: "Buenos Aires Transition Half Real",
    compositionCode: "silver-900",
    currencyCode: "real",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.5,
    faceValueText: "Half Real",
    issuerCode: "buenos-aires",
    weight: 3.8,
    diameter: 18.5,
    thickness: 1.4,
    minYear: -2,
    maxYear: 0,
    createdAt: new Date("2026-01-08T00:00:00.000Z"),
    updatedAt: new Date("2026-01-08T00:00:00.000Z"),
  },
  {
    title: "United States Flowing Hair Dollar",
    compositionCode: "silver-900",
    currencyCode: "united-states-dollar",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Dollar",
    issuerCode: "united-states",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "lettered",
    techniqueCode: "milled",
    weight: 26.73,
    diameter: 39,
    thickness: 2.9,
    minYear: 1793,
    maxYear: 1795,
    createdAt: new Date("2026-01-09T00:00:00.000Z"),
    updatedAt: new Date("2026-01-09T00:00:00.000Z"),
  },
  {
    title: "Argentina Convertible Peso",
    comments: null,
    compositionCode: "copper-nickel",
    currencyCode: "argentine-peso",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Peso",
    issuerCode: "argentina",
    techniqueCode: "milled",
    weight: 6.35,
    diameter: 23.5,
    thickness: 1.9,
    minYear: 2001,
    maxYear: 2001,
    createdAt: new Date("2026-01-10T00:00:00.000Z"),
    updatedAt: new Date("2026-01-10T00:00:00.000Z"),
  },
  {
    title: "Spain 2 Euro",
    comments:
      "Common circulating commemorative format with a national obverse and shared euro reverse.",
    compositionCode: "copper-nickel-clad",
    currencyCode: "euro",
    distributionCode: "circulating-commemorative",
    edgeCode: "lettered",
    faceValueNumericValue: 2,
    faceValueText: "2 Euros",
    issuerCode: "spain",
    isDemonetized: false,
    mintage: 50000000,
    orientationCode: "medal-alignment",
    techniqueCode: "milled",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    weight: 8.5,
    diameter: 25.75,
    thickness: 2.2,
    minYear: 2015,
    maxYear: 2026,
    createdAt: new Date("2026-01-11T00:00:00.000Z"),
    updatedAt: new Date("2026-01-11T00:00:00.000Z"),
  },
  {
    comments: "Fifth Enlargement of the European Union",
    compositionCode: "bimetallic",
    currencyCode: "euro",
    diameter: 25.75,
    distributionCode: "circulating-commemorative",
    edgeCode: "lettered-signs-numbers-reeded",
    faceValueNumericValue: 2,
    faceValueText: "2 Euros",
    isDemonetized: false,
    issuerCode: "finland",
    maxYear: 2004,
    minYear: 2004,
    mintage: 1000000,
    orientationCode: "medal-alignment",
    rimCode: "raised-not-decorated-both-sides",
    shapeCode: "circular",
    techniqueCode: "milled",
    thickness: 2.2,
    title: "2 Euros (Enlargement of the European Union)",
    weight: 8.5,
    createdAt: new Date("1987-08-24T00:00:00.000Z"),
    updatedAt: new Date("1987-08-24T00:00:00.000Z"),
  },
  {
    title: "Spain 1 Euro",
    compositionCode: "bimetallic",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Euro",
    issuerCode: "spain",
    orientationCode: "medal-alignment",
    shapeCode: "round",
    rimCode: "raised-not-decorated-both-sides",
    techniqueCode: "milled",
    weight: 7.5,
    diameter: 23.25,
    thickness: 2.33,
    minYear: 1999,
    maxYear: 2026,
    createdAt: new Date("2026-01-12T00:00:00.000Z"),
    updatedAt: new Date("2026-01-12T00:00:00.000Z"),
  },
  {
    title: "Spain 50 Euro Cent",
    compositionCode: "copper-nickel-clad",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.5,
    faceValueText: "50 Euro Cent",
    issuerCode: "spain",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 7.8,
    diameter: 24.25,
    thickness: 2.38,
    minYear: 1999,
    maxYear: 2026,
    createdAt: new Date("2026-01-13T00:00:00.000Z"),
    updatedAt: new Date("2026-01-13T00:00:00.000Z"),
  },
  {
    title: "Spain 10 Euro Cent",
    compositionCode: "copper",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.1,
    faceValueText: "10 Euro Cent",
    issuerCode: "spain",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 4.1,
    diameter: 19.75,
    thickness: 1.93,
    minYear: 1999,
    maxYear: 2026,
    createdAt: new Date("2026-01-14T00:00:00.000Z"),
    updatedAt: new Date("2026-01-14T00:00:00.000Z"),
  },
  {
    title: "Finland 2 Euro",
    compositionCode: "bimetallic",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 2,
    faceValueText: "2 Euro",
    issuerCode: "finland",
    orientationCode: "medal-alignment",
    shapeCode: "round",
    rimCode: "lettered",
    techniqueCode: "milled",
    weight: 8.5,
    diameter: 25.75,
    thickness: 2.2,
    minYear: 2002,
    maxYear: 2026,
    createdAt: new Date("2026-01-15T00:00:00.000Z"),
    updatedAt: new Date("2026-01-15T00:00:00.000Z"),
  },
  {
    title: "Finland 1 Euro",
    compositionCode: "bimetallic",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Euro",
    issuerCode: "finland",
    orientationCode: "medal-alignment",
    shapeCode: "round",
    rimCode: "raised-not-decorated-both-sides",
    techniqueCode: "milled",
    weight: 7.5,
    diameter: 23.25,
    thickness: 2.33,
    minYear: 2002,
    maxYear: 2026,
    createdAt: new Date("2026-01-16T00:00:00.000Z"),
    updatedAt: new Date("2026-01-16T00:00:00.000Z"),
  },
  {
    title: "Finland 50 Euro Cent",
    compositionCode: "copper-nickel-clad",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.5,
    faceValueText: "50 Euro Cent",
    issuerCode: "finland",
    orientationCode: "medal-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 7.8,
    diameter: 24.25,
    thickness: 2.38,
    minYear: 2002,
    maxYear: 2026,
    createdAt: new Date("2026-01-17T00:00:00.000Z"),
    updatedAt: new Date("2026-01-17T00:00:00.000Z"),
  },
  {
    title: "United States Washington Quarter",
    compositionCode: "copper-nickel-clad",
    currencyCode: "united-states-dollar",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.25,
    faceValueText: "Quarter Dollar",
    issuerCode: "united-states",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 5.67,
    diameter: 24.26,
    thickness: 1.75,
    minYear: 1932,
    maxYear: 2026,
    createdAt: new Date("2026-01-18T00:00:00.000Z"),
    updatedAt: new Date("2026-01-18T00:00:00.000Z"),
  },
  {
    title: "United States Sacagawea Dollar",
    compositionCode: "bimetallic",
    currencyCode: "united-states-dollar",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Dollar",
    issuerCode: "united-states",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "plain",
    techniqueCode: "milled",
    weight: 8.1,
    diameter: 26.5,
    thickness: 2.0,
    minYear: 2000,
    maxYear: 2026,
    createdAt: new Date("2026-01-19T00:00:00.000Z"),
    updatedAt: new Date("2026-01-19T00:00:00.000Z"),
  },
  {
    title: "United States Buffalo Nickel",
    compositionCode: "copper-nickel",
    currencyCode: "united-states-dollar",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.05,
    faceValueText: "5 Cents",
    issuerCode: "united-states",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "plain",
    techniqueCode: "milled",
    weight: 5,
    diameter: 21.2,
    thickness: 1.95,
    minYear: 1913,
    maxYear: 1938,
    createdAt: new Date("2026-01-20T00:00:00.000Z"),
    updatedAt: new Date("2026-01-20T00:00:00.000Z"),
  },
  {
    title: "Argentina 10 Centavos",
    compositionCode: "copper-nickel",
    currencyCode: "argentine-peso",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.1,
    faceValueText: "10 Centavos",
    issuerCode: "argentina",
    weight: 5.4,
    diameter: 21,
    thickness: 1.7,
    minYear: 1896,
    maxYear: 1898,
    createdAt: new Date("2026-01-21T00:00:00.000Z"),
    updatedAt: new Date("2026-01-21T00:00:00.000Z"),
  },
  {
    title: "Argentina 50 Centavos",
    compositionCode: "silver-900",
    currencyCode: "argentine-peso",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.5,
    faceValueText: "50 Centavos",
    issuerCode: "argentina",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "hammered",
    weight: 12.4,
    diameter: 31,
    thickness: 2.5,
    minYear: 1896,
    maxYear: 1898,
    createdAt: new Date("2026-01-22T00:00:00.000Z"),
    updatedAt: new Date("2026-01-22T00:00:00.000Z"),
  },
  {
    title: "Argentina 2 Pesos",
    compositionCode: "copper-nickel-clad",
    currencyCode: "argentine-peso",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 2,
    faceValueText: "2 Pesos",
    issuerCode: "argentina",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 5.2,
    diameter: 20.5,
    thickness: 1.8,
    minYear: 1994,
    maxYear: 2026,
    createdAt: new Date("2026-01-23T00:00:00.000Z"),
    updatedAt: new Date("2026-01-23T00:00:00.000Z"),
  },
  {
    title: "Buenos Aires 2 Reales",
    compositionCode: "silver-900",
    currencyCode: "real",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 2,
    faceValueText: "2 Reales",
    issuerCode: "buenos-aires",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "lettered",
    techniqueCode: "hammered",
    weight: 13.6,
    diameter: 33,
    thickness: 2.3,
    minYear: 1812,
    maxYear: 1814,
    createdAt: new Date("2026-01-24T00:00:00.000Z"),
    updatedAt: new Date("2026-01-24T00:00:00.000Z"),
  },
  {
    title: "Buenos Aires 1 Real",
    compositionCode: "silver-900",
    currencyCode: "real",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 1,
    faceValueText: "1 Real",
    issuerCode: "buenos-aires",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "plain",
    techniqueCode: "hammered",
    weight: 6.8,
    diameter: 28,
    thickness: 1.9,
    minYear: 1812,
    maxYear: 1814,
    createdAt: new Date("2026-01-25T00:00:00.000Z"),
    updatedAt: new Date("2026-01-25T00:00:00.000Z"),
  },
  {
    title: "Buenos Aires 2 Decimos",
    compositionCode: "silver-900",
    currencyCode: "real",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.2,
    faceValueText: "2 Decimos",
    issuerCode: "buenos-aires",
    weight: 2.7,
    diameter: 16,
    thickness: 1.2,
    minYear: 1821,
    maxYear: 1823,
    createdAt: new Date("2026-01-26T00:00:00.000Z"),
    updatedAt: new Date("2026-01-26T00:00:00.000Z"),
  },
  {
    title: "Finland 10 Euro Cent",
    compositionCode: "copper",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.1,
    faceValueText: "10 Euro Cent",
    issuerCode: "finland",
    orientationCode: "medal-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 4.1,
    diameter: 19.75,
    thickness: 1.93,
    minYear: 2002,
    maxYear: 2026,
    createdAt: new Date("2026-01-27T00:00:00.000Z"),
    updatedAt: new Date("2026-01-27T00:00:00.000Z"),
  },
  {
    title: "Spain 5 Euro Cent",
    compositionCode: "copper",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.05,
    faceValueText: "5 Euro Cent",
    issuerCode: "spain",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "plain",
    techniqueCode: "milled",
    weight: 3.92,
    diameter: 21.25,
    thickness: 1.67,
    minYear: 1999,
    maxYear: 2026,
    createdAt: new Date("2026-01-28T00:00:00.000Z"),
    updatedAt: new Date("2026-01-28T00:00:00.000Z"),
  },
  {
    title: "Spain 20 Euro Cent",
    compositionCode: "copper",
    currencyCode: "euro",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.2,
    faceValueText: "20 Euro Cent",
    issuerCode: "spain",
    orientationCode: "coin-alignment",
    shapeCode: "scalloped",
    rimCode: "raised-not-decorated-both-sides",
    techniqueCode: "milled",
    weight: 5.74,
    diameter: 22.25,
    thickness: 2.14,
    minYear: 1999,
    maxYear: 2026,
    createdAt: new Date("2026-01-29T00:00:00.000Z"),
    updatedAt: new Date("2026-01-29T00:00:00.000Z"),
  },
  {
    title: "United States Mercury Dime",
    compositionCode: "silver-900",
    currencyCode: "united-states-dollar",
    distributionCode: "standard-circulation",
    faceValueNumericValue: 0.1,
    faceValueText: "10 Cents",
    issuerCode: "united-states",
    orientationCode: "coin-alignment",
    shapeCode: "round",
    rimCode: "raised-both-sides",
    techniqueCode: "milled",
    weight: 2.5,
    diameter: 17.9,
    thickness: 1.35,
    minYear: 1916,
    maxYear: 1945,
    createdAt: new Date("2026-01-30T00:00:00.000Z"),
    updatedAt: new Date("2026-01-30T00:00:00.000Z"),
  },
]
