import type { SeededIssuer } from "./types"

const seededAt = new Date("2026-01-01T00:00:00.000Z")

export const seededIssuers: SeededIssuer[] = [
  {
    code: "germany",
    name: "Germany",
    isoCode: "DE",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "andorra",
    name: "Andorra",
    isoCode: "AD",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "austria",
    name: "Austria",
    isoCode: "AT",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "belgium",
    name: "Belgium",
    isoCode: "BE",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "cyprus",
    name: "Cyprus",
    isoCode: "CY",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "croatia",
    name: "Croatia",
    isoCode: "HR",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "slovakia",
    name: "Slovakia",
    isoCode: "SK",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "slovenia",
    name: "Slovenia",
    isoCode: "SI",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "spain",
    name: "Spain",
    isoCode: "ES",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "estonia",
    name: "Estonia",
    isoCode: "EE",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "finland",
    name: "Finland",
    isoCode: "FI",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "france",
    name: "France",
    isoCode: "FR",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "greece",
    name: "Greece",
    isoCode: "GR",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "ireland",
    name: "Ireland",
    isoCode: "IE",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "italy",
    name: "Italy",
    isoCode: "IT",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "latvia",
    name: "Latvia",
    isoCode: "LV",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "lithuania",
    name: "Lithuania",
    isoCode: "LT",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "luxembourg",
    name: "Luxembourg",
    isoCode: "LU",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "malta",
    name: "Malta",
    isoCode: "MT",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "monaco",
    name: "Monaco",
    isoCode: "MC",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "netherlands",
    name: "Netherlands",
    isoCode: "NL",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "portugal",
    name: "Portugal",
    isoCode: "PT",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "san-marino",
    name: "San Marino",
    isoCode: "SM",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    code: "vatican-city",
    name: "Vatican City",
    isoCode: "VA",
    createdAt: seededAt,
    updatedAt: seededAt,
  },
]
