/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDatabaseRouteImport } from './routes/_authed/database'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicCoinsCoinIdRouteImport } from './routes/(public)/coins.$coinId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDatabaseRoute = AuthedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCoinsCoinIdRoute = publicCoinsCoinIdRouteImport.update({
  id: '/(public)/coins/$coinId',
  path: '/coins/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginRoute
  '/database': typeof AuthedDatabaseRoute
  '/settings': typeof AuthedSettingsRoute
  '/coins/$coinId': typeof publicCoinsCoinIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginRoute
  '/database': typeof AuthedDatabaseRoute
  '/settings': typeof AuthedSettingsRoute
  '/coins/$coinId': typeof publicCoinsCoinIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/_authed/database': typeof AuthedDatabaseRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/coins/$coinId': typeof publicCoinsCoinIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/database'
    | '/settings'
    | '/coins/$coinId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/database'
    | '/settings'
    | '/coins/$coinId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/(public)/login'
    | '/_authed/database'
    | '/_authed/settings'
    | '/(public)/'
    | '/(public)/coins/$coinId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicIndexRoute: typeof publicIndexRoute
  publicCoinsCoinIdRoute: typeof publicCoinsCoinIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/database': {
      id: '/_authed/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthedDatabaseRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/coins/$coinId': {
      id: '/(public)/coins/$coinId'
      path: '/coins/$coinId'
      fullPath: '/coins/$coinId'
      preLoaderRoute: typeof publicCoinsCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDatabaseRoute: typeof AuthedDatabaseRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDatabaseRoute: AuthedDatabaseRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicIndexRoute: publicIndexRoute,
  publicCoinsCoinIdRoute: publicCoinsCoinIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
