/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JsonRouteImport } from './routes/json'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoinsCoinIdRouteImport } from './routes/coins.$coinId'

const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsCoinIdRoute = CoinsCoinIdRouteImport.update({
  id: '/coins/$coinId',
  path: '/coins/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/json': typeof JsonRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/json': typeof JsonRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/json': typeof JsonRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/json' | '/coins/$coinId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/json' | '/coins/$coinId'
  id: '__root__' | '/' | '/json' | '/coins/$coinId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JsonRoute: typeof JsonRoute
  CoinsCoinIdRoute: typeof CoinsCoinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins/$coinId': {
      id: '/coins/$coinId'
      path: '/coins/$coinId'
      fullPath: '/coins/$coinId'
      preLoaderRoute: typeof CoinsCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JsonRoute: JsonRoute,
  CoinsCoinIdRoute: CoinsCoinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
